### ISSUE TITLE
ldap.toml group_mappings are deep sorted

### ISSUE THREAD

**Issue by HP41** [sous-chefs/chef-grafana#417]
## :ghost: Brief Description

Group mappings per server are deep sorted and can cause issues as the first group to match will be used as described by grafana official docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/#group-mappings.

## :pancakes: Cookbook version

Latest as of writing this: `10.0.4`

## :woman_cook:  Chef-Infra Version

```
cinc-client --version
Cinc Client: 16.18.0
```

## :tophat: Platform details

Standard Ubuntu 18.04 and 20.04 in test kitchen

## Steps To Reproduce

```ruby
# resource declarations
grafana_config_ldap_server 'grafana-dev' do
  host 'ad1.tdomain.com'
  bind_dn 'TESTDOMAIN\\%s'
  search_filter '(sAMAccountName=%s)'
  search_base_dns %w[DC=testdomain,DC=tdomain,DC=com]
  use_ssl false
  start_tls false
end

grafana_config_ldap_attributes 'grafana-dev' do
  host  'ad1.tdomain.com'
  attribute_name 'givenName'
  attribute_surname 'sn'
  attribute_username 'sAMAccountName'
  attribute_member_of 'memberOf'
  attribute_email 'mail'
end

grafana_config_ldap_group_mapping 'Admin role' do
  host 'ad1.tdomain.com'
  group_dn 'CN=TDomainAdmins,OU=UserGroups,DC=testdomain,DC=tdomain,DC=com'
  org_role 'Admin'
  org_id 1
  grafana_admin true
end

grafana_config_ldap_group_mapping 'Viewer role' do
  host 'ad1.tdomain.com'
  group_dn 'CN=TDomain,OU=UserGroups,DC=testdomain,DC=tdomain,DC=com'
  org_role 'Viewer'
  org_id 1
  grafana_admin false
end
```

```toml
# /etc/grafana/ldap.toml
[[servers]]
bind_dn = "TESTDOMAIN\\%s"
host = "ad1.tdomain.com"
port = 389
search_base_dns = ["DC=testdomain,DC=tdomain,DC=com"]
search_filter = "(sAMAccountName=%s)"
start_tls = false
use_ssl = false
[servers.attributes]
email = "mail"
member_of = "memberOf"
name = "givenName"
surname = "sn"
username = "sAMAccountName"
[[servers.group_mappings]]
grafana_admin = false
group_dn = "CN=TDomain,OU=UserGroups,DC=testdomain,DC=tdomain,DC=com"
org_id = 1
org_role = "Viewer"
[[servers.group_mappings]]
grafana_admin = true
group_dn = "CN=TDomainAdmins,OU=UserGroups,DC=testdomain,DC=tdomain,DC=com"
org_id = 1
org_role = "Admin"
```

## :police_car: Expected behavior

The order of the group_mappings in `/etc/grafana/ldap.toml` must honour the order in which the resources were declared to ensure grafana's ldap group_mappings logic works as expected
